apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: resttest-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: resttest
    spec:
      containers:
      - image: staticblast/msvc-test:v2
        imagePullPolicy: Always 
        name: resttest-deployment
        ports:
        - containerPort: 8090
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 30
          timeoutSeconds: 10
          httpGet:
            path: /actuator/health
            port: 8090